export const podcastNames = [
  {
    subscribers: 4748,
    name: 'venus',
    label: 'VenusPodcast',
    creator_profile_id: 'mL0SV0pP2YtOeXxjWe2P',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/mL0SV0pP2YtOeXxjWe2P/assets/images/xoqrwbzA6e.png',
  },
  {
    subscribers: 2453,
    name: 'flow',
    label: 'Flow',
    creator_profile_id: '25x0SqMaSNXgwv14g0Xg',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/25x0SqMaSNXgwv14g0Xg/assets/images/j-o2CbKjMl.png',
  },
  {
    subscribers: 1864,
    name: 'flowsportclub',
    label: 'Flow Sport Club',
    creator_profile_id: 'XzHIWZr50PSQJ6i47kVd',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/XzHIWZr50PSQJ6i47kVd/assets/icon/37bf9803-af20-40bb-9b7b-5f1df9d09618_76c82417-561e-4183-9fcc-ca270ebadf74_daf24121-6c86-4ed7-bb66-770d87d3e4c8.jpeg',
  },
  {
    subscribers: 1836,
    name: 'cienciasemfim',
    label: 'Ciência Sem Fim',
    creator_profile_id: 'yLTB8ibDV92MmwQMNHQD',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/yLTB8ibDV92MmwQMNHQD/assets/icon/e8abc3c7-0506-48c7-958e-72e4aa303602_89e6a595-3cb6-4118-be90-b26bff2d42da_e6a931f5-e7d1-4a75-b1f6-bd799cb328ca.jpeg',
  },
  {
    subscribers: 1648,
    name: 'kritikepodcast',
    label: 'Kritikê Podcast',
    creator_profile_id: 'ac7TKXX0pZ928KiXFzrL',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/ac7TKXX0pZ928KiXFzrL/assets/images/abSX3VvCDY.png',
  },
  {
    subscribers: 1323,
    name: 'flowgames',
    label: 'Flow Games',
    creator_profile_id: '2mXVl9k4sEbrBKrvwDtL',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/2mXVl9k4sEbrBKrvwDtL/assets/images/sHy5JWRHzW.png',
  },
  {
    subscribers: 1292,
    name: 'amplifica',
    label: 'Canal Amplifica',
    creator_profile_id: '43aCjGDJFpqZeFRaVJX9',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/43aCjGDJFpqZeFRaVJX9/assets/images/MA_rtg8Uy2.jpeg',
  },
  {
    subscribers: 1264,
    name: 'tocadoelfo',
    label: 'Toca do Elfo',
    creator_profile_id: 'elxu2TNruyiJGBIL56el',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/elxu2TNruyiJGBIL56el/assets/images/Bqu5xkyICc.jpeg',
  },
  {
    subscribers: 1108,
    name: 'renejotas',
    label: 'Rene e Jotas',
    creator_profile_id: 'P2SEdHsEtEBF4QSglVdv',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/P2SEdHsEtEBF4QSglVdv/assets/images/6gu6yBa78t.png',
  },
  {
    subscribers: 1058,
    name: 'nv99',
    label: 'NV99',
    creator_profile_id: 'lnB5tRq9MI5bfPGDOIie',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/lnB5tRq9MI5bfPGDOIie/assets/images/0mIS3kuJui.png',
  },
  {
    subscribers: 1028,
    name: '3irmaos',
    label: '3 Irmãos',
    creator_profile_id: 'g6TB80IQZR17fkk29gMd',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/g6TB80IQZR17fkk29gMd/assets/images/pgZ0k1ouZ7.png',
  },
  {
    subscribers: 1015,
    name: 'warriors',
    label: 'Warriors Game House',
    creator_profile_id: 'RagbjuOaIGgBjnt1470Y',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/RagbjuOaIGgBjnt1470Y/assets/images/qUo2B3LmRf.png',
  },
  {
    subscribers: 1011,
    name: 'prosaguiada',
    label: 'Prosa Guiada',
    creator_profile_id: 'Wr8kAod7FUvG4vF8Z1es',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/Wr8kAod7FUvG4vF8Z1es/assets/images/Xng2D16iGh.jpeg',
  },
  {
    subscribers: 962,
    name: 'estudiosflow',
    label: 'Estúdios Flow',
    creator_profile_id: '2QfGAsD7OzgO4TKMg2Hb',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/2QfGAsD7OzgO4TKMg2Hb/assets/images/gN6AomORRd.jpeg',
  },
  {
    subscribers: 891,
    name: 'nerdsobrerodas',
    label: 'Nerd Sobre Rodas',
    creator_profile_id: 'gunlRsDWsJqbk6yp1eNG',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/gunlRsDWsJqbk6yp1eNG/assets/images/6LxWFNBq2Y.jpeg',
  },
  {
    subscribers: 691,
    name: 'noir',
    label: 'Noir Podcast',
    creator_profile_id: 'yRIU2ONnLFuaAIA9qQT4',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/yRIU2ONnLFuaAIA9qQT4/assets/icon/3c1d6811-fd87-4eec-af9a-764f773254ba_21c0c767-88bc-4cbb-931a-2a5d39694134_c4ed7a85-6805-476b-9351-5e5b3bd9b52d.jpeg',
  },
  {
    subscribers: 641,
    name: 'omniverso',
    label: 'Omniverso',
    creator_profile_id: 'qjG7wExpFL45fEm2sNRx',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/qjG7wExpFL45fEm2sNRx/assets/images/m7lmYfg3cg.png',
  },
  {
    subscribers: 640,
    name: 'ssf',
    label: 'Salve Salve Família',
    creator_profile_id: 'AJ3kQcRI99aa4SlqlyaN',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/AJ3kQcRI99aa4SlqlyaN/assets/images/g3E0TkZU1s.jpeg',
  },
  {
    subscribers: 624,
    name: 'flowpoop',
    label: 'Flow Poop [OFICIAL]',
    creator_profile_id: '8EFNoYh08r3LAhhQGH4T',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/8EFNoYh08r3LAhhQGH4T/assets/images/XGm89t7HVq.jpeg',
  },
  {
    subscribers: 622,
    name: 'podcastnordestino',
    label: 'Podcast Nordestino',
    creator_profile_id: 'MfXp84HYmYGhTMDYFImc',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/MfXp84HYmYGhTMDYFImc/assets/images/uTWyeuicLW.jpeg',
  },
  {
    subscribers: 573,
    name: 'nv99devs',
    label: 'NV99 - Devs',
    creator_profile_id: 'qCvZkm48UzemFtNM1Lh4',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/lnB5tRq9MI5bfPGDOIie/assets/images/0mIS3kuJui.png',
  },
  {
    subscribers: 568,
    name: 'meiameiashow',
    label: 'Meia Meia',
    creator_profile_id: 'bpHOyXjSkSofHkRALswU',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/bpHOyXjSkSofHkRALswU/assets/images/C_oAUzBhFq.png',
  },
  {
    subscribers: 550,
    name: 'flowlabs',
    label: 'FLOW LABS',
    creator_profile_id: 'GT0e6IF2DCR1ufd6VHMX',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/GT0e6IF2DCR1ufd6VHMX/assets/images/qQPEVQcVb9.jpeg',
  },
  {
    subscribers: 545,
    name: 'gameplayrj',
    label: 'Gameplayrj',
    creator_profile_id: '7C3rzgXAgcPjcSzAYuV3',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/7C3rzgXAgcPjcSzAYuV3/assets/images/QSpZuI4DWr.jpeg',
  },
  {
    subscribers: 531,
    name: 'avesso',
    label: 'Avesso Podcast',
    creator_profile_id: '5szJJj1QeIWw4Pm6tiLB',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/5szJJj1QeIWw4Pm6tiLB/assets/icon/4e76a03d-091e-44d8-b716-15875097de4e_b9eed3ce-67cc-45c0-b0f2-144867918c03_5124eeb6-9f84-440c-a18e-97c2e3f90304.jpeg',
  },
  {
    subscribers: 515,
    name: 'davyjones',
    label: 'Davy Jones',
    creator_profile_id: 'LFwBCrMUTIirRwlLFnp4',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/LFwBCrMUTIirRwlLFnp4/assets/images/YM4Bac0tPa.jpeg',
  },
  {
    subscribers: 509,
    name: 'gianzao',
    label: 'Gianzão',
    creator_profile_id: 'L9iM8ZwVJhN4C3gj8ep5',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/L9iM8ZwVJhN4C3gj8ep5/assets/images/CLdoX-txoD.png',
  },
  {
    subscribers: 491,
    name: 'tonelive',
    label: 'Tonelive',
    creator_profile_id: 'teHRVwzvqpzzLYfTDPK1',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/teHRVwzvqpzzLYfTDPK1/assets/images/rpNklxF4Og.png',
  },
  {
    subscribers: 490,
    name: 'vintageculture',
    label: 'Vintage Culture',
    creator_profile_id: 'La6VHCfaPXcVDlHsfGZt',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/La6VHCfaPXcVDlHsfGZt/assets/images/WMyeGhz8mx.png',
  },
  {
    subscribers: 460,
    name: 'ricardoohara',
    label: 'Ricardo Ohara',
    creator_profile_id: 'pZwmcAQO6oxGtz5ebii2',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/pZwmcAQO6oxGtz5ebii2/assets/images/2JF6xZikP0.jpeg',
  },
  {
    subscribers: 441,
    name: 'desvetados',
    label: 'Desvetados',
    creator_profile_id: 'b8ApuoAa6uo03o0RYEQP',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/b8ApuoAa6uo03o0RYEQP/assets/images/iFEZGxBWSj.jpeg',
  },
  {
    subscribers: 441,
    name: 'bateponto',
    label: 'Bate Ponto',
    creator_profile_id: 'aFl5c53BxnUj1q899HXX',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/aFl5c53BxnUj1q899HXX/assets/images/IOJ1MO-j2_.jpeg',
  },
  {
    subscribers: 441,
    name: 'd2xpbrazil',
    label: 'D2XP Brazil',
    creator_profile_id: 'KXyi6ItEDvW6z1rsdfBa',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/KXyi6ItEDvW6z1rsdfBa/assets/icon/9267b70e-e241-4eec-a501-903991097829_0c8ca89e-ab02-4893-8224-58627dec8367_0c68dbe3-bd12-4cc9-96ed-aab732f60e3c.jpeg',
  },
  {
    subscribers: 414,
    name: 'brat',
    label: 'BRAT',
    creator_profile_id: 'HKMh8MyFL4Pi9TABRUpe',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/HKMh8MyFL4Pi9TABRUpe/assets/images/nZGUgCKrZh.jpeg',
  },
  {
    subscribers: 398,
    name: 'carlostramontina',
    label: 'Carlos Tramontina',
    creator_profile_id: 'Geqck3tHNXMifxAShdpm',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/Geqck3tHNXMifxAShdpm/assets/images/KQeK_M2IOp.jpeg',
  },
  {
    subscribers: 281,
    name: 'nepo',
    label: 'Fala Nepo',
    creator_profile_id: 'mfxuP9JS2cy50JFOshtZ',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/mfxuP9JS2cy50JFOshtZ/assets/images/QiItIr3ZUJ.jpeg',
  },
  {
    subscribers: 225,
    name: 'decosuete',
    label: 'Deco Suete',
    creator_profile_id: 'dCr9NJNmh6kwikKRioxR',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/dCr9NJNmh6kwikKRioxR/assets/images/wnFY7yU-y6.png',
  },
  {
    subscribers: 193,
    name: 'castarretado',
    label: 'Cast Arretado',
    creator_profile_id: '71NaKOFWS2xuZawtIu0I',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/71NaKOFWS2xuZawtIu0I/assets/images/WIZ_MOg0-Z.jpeg',
  },
  {
    subscribers: 172,
    name: 'ademiro',
    label: 'ADEMIRO',
    creator_profile_id: 'NKJCMbgX8hq2oe2MP6Y5',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/NKJCMbgX8hq2oe2MP6Y5/assets/images/yAqPWo9ch5.jpeg',
  },
  {
    subscribers: 120,
    name: 'sociedadenerd',
    label: 'Sociedade Nerd',
    creator_profile_id: 'c7a5SAaYBYpnOpTtlisK',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/c7a5SAaYBYpnOpTtlisK/assets/images/fj5IUIvGsZ.jpeg',
  },
  {
    subscribers: 101,
    name: 'torradeiratv',
    label: 'TorradeiraTV',
    creator_profile_id: 'p4n3n1wwvRfl1ZPnJ6LJ',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/p4n3n1wwvRfl1ZPnJ6LJ/assets/images/WfoZtCaZQ2.jpeg',
  },
  {
    subscribers: 79,
    name: 'amoacoes',
    label: 'Amo Ações',
    creator_profile_id: 'ZN66Pb7cy9M6Ra1oMFBV',
    subscribed: false,
    icon: 'https://cdn.flowpodcast.com.br/criador/ZN66Pb7cy9M6Ra1oMFBV/assets/images/J-N57Cymll.jpeg',
  },
];

export function verifyPodcast(podcast: string) {
  const podcastName = podcastNames.find(
    (podcastName) => podcastName.creator_profile_id === podcast,
  );
  return podcastName ? podcastName.label : 'Podcast não encontrado';
}
